version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=curriculos_db
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: mysql:8.0.34-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: curriculos_db
    networks:
      - app-network
      
networks:
  app-network:

volumes:
  db_data:
